module.exports = {
	extends: ["stylelint-config-standard", "stylelint-config-standard-scss"],
	plugins: [
		"stylelint-scss",
		"stylelint-selector-bem-pattern",
		"stylelint-declaration-strict-value",
		"stylelint-order",
	],
	rules: {
		"selector-pseudo-element-no-unknown": null,
		"scss/at-extend-no-missing-placeholder": null,
		"property-no-vendor-prefix": null,
		"declaration-colon-newline-after": null,
		"color-function-notation": "legacy",
		"unit-allowed-list": ["em", "rem", "%", "s", "deg", "vh"],
		"alpha-value-notation": [
			"percentage",
			{ exceptProperties: ["opacity"] },
		],
		"selector-class-pattern":
			"^[A-Z][A-Za-z\\d]*(__[A-Z][A-Za-z\\d]*)?(--[A-Z][A-Za-z\\d]*)?$",
		"indentation": null,
		"plugin/selector-bem-pattern": {
			implicitComponents: "components/**/*.scss",
		},
		"scale-unlimited/declaration-strict-value": [
			[
				"/color/",
				"fill",
				"stroke",
				"z-index",
				"/font/",
				"box-shadow",
				"/border/",
				"/padding/",
				"/margin/",
				"/gap/",
			],
			{
				ignoreValues: [
					"solid",
					"transparent",
					"currentColor",
					"inherit",
					"smaller",
					"none",
					"0",
					"calc()",
					"calc",
					"auto",
					"italic",
				],
			},
		],
		"order/order": [
			"at-variables",
			"dollar-variables",
			{
				type: "at-rule",
				name: "include",
				hasBlock: false,
			},
			"custom-properties",
			"declarations",
			"rules",
			{
				type: "at-rule",
				name: "include",
				hasBlock: true,
			},
		],
		"order/properties-order": [
			[
				{
					emptyLineBefore: "always",
					properties: [
						"position",
						"top",
						"right",
						"bottom",
						"left",
						"z-index",
						"transform",
						"transition",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"display",
						"box-sizing",
						"float",
						"width",
						"height",
						"max-width",
						"max-height",
						"min-width",
						"min-height",
						"overflow",
						"overflow-x",
						"overflow-y",
						"clip",
						"clear",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"order",
						"flex",
						"flex-grow",
						"flex-shrink",
						"flex-basis",
						"align-self",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"grid",
						"grid-template",
						"grid-template-columns",
						"grid-template-rows",
						"grid-column",
						"grid-row",
						"grid-area",
						"grid-column-start",
						"grid-column-end",
						"grid-row-start",
						"grid-row-end",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"flex-flow",
						"flex-direction",
						"flex-wrap",
						"justify-content",
						"align-items",
						"align-content",
						"gap",
						"column-gap",
						"row-gap",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"font",
						"font-size",
						"font-family",
						"font-weight",
						"font-style",
						"font-variant",
						"font-display",
						"line-height",
						"letter-spacing",
						"text-transform",
						"text-align",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"color",
						"background-color",
						"background",
						"background-image",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"padding",
						"padding-top",
						"padding-right",
						"padding-bottom",
						"padding-left",
					],
				},
				{
					emptyLineBefore: "always",
					properties: [
						"margin",
						"margin-top",
						"margin-right",
						"margin-bottom",
						"margin-left",
						"margin-collapse",
						"margin-top-collapse",
						"margin-right-collapse",
						"margin-bottom-collapse",
						"margin-left-collapse",
					],
				},
			],
			{ unspecified: "bottom" },
		],
		"scss/at-else-closing-brace-newline-after": "always-last-in-chain",
		"scss/at-else-closing-brace-space-after": "always-intermediate",
		"scss/at-else-empty-line-before": "never",
		"scss/at-function-pattern": "[a-z]+(:?-[a-z]+)*",
		"scss/at-if-closing-brace-newline-after": "always-last-in-chain",
		"scss/at-if-closing-brace-space-after": "always-intermediate",
		"scss/at-import-no-partial-leading-underscore": true,
		"scss/at-import-partial-extension-blacklist": ["scss"],
		"scss/at-mixin-argumentless-call-parentheses": "always",
		"scss/at-mixin-pattern": "[a-z]+(:?-[a-z]+)*",
		"scss/at-rule-no-unknown": true,
		"scss/dollar-variable-colon-newline-after": null,
		"scss/dollar-variable-colon-space-after": "always-single-line",
		"scss/dollar-variable-colon-space-before": "never",
		"scss/dollar-variable-no-missing-interpolation": true,
		"scss/dollar-variable-pattern": "[a-z]+(:?-[a-z]+)*",
		"scss/percent-placeholder-pattern": "[a-z]+(:?-[a-z]+)*",
		"scss/double-slash-comment-empty-line-before": [
			"always",
			{
				except: ["first-nested"],
				ignore: ["between-comments", "stylelint-commands"],
			},
		],
		"scss/double-slash-comment-whitespace-inside": "always",
		"scss/operator-no-newline-after": true,
		"scss/operator-no-newline-before": true,
		"scss/operator-no-unspaced": true,
		"scss/selector-no-redundant-nesting-selector": true,
		"scss/declaration-nested-properties": "never",
		"at-rule-empty-line-before": [
			"always",
			{
				except: ["blockless-after-same-name-blockless", "first-nested"],
				ignore: ["after-comment", "blockless-after-blockless"],
				ignoreAtRules: ["if", "else"],
			},
		],
		"at-rule-no-unknown": null,
		"selector-type-no-unknown": null,
		"declaration-empty-line-before": null,
		"block-closing-brace-newline-after": [
			"always",
			{
				ignoreAtRules: ["if", "else"],
			},
		],
		"block-closing-brace-space-after": null,
		"block-no-empty": null,
		"max-empty-lines": [
			2,
			{
				ignore: ["comments"],
			},
		],
	},
	ignore: [
		"**/*.js",
		"**/*.json",
		"**/*.html",
		"node_modules",
		"public",
		".next",
		"coverage",
		"dist",
		".turbo",
		"scripts",
		"vite.config.ts",
	],
};
